<a href="https://colab.research.google.com/github/Acabre21/machineLearning/blob/master/HW_4/Problems1%262.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Problem 1

Using only numpy, implement the function conv2d. It takes as input input_mat and kernel_mat and outputs output_mat. All variables are square matrices. It should compute the convolution of input_mat with the kernel kernel_mat using valid padding.

In [0]:
class MatrixError(Exception):
  def __init__(self, *args):
    if args: 
      self.message = args[0]
    else:
      self.message = None
  def __str__(self):
    if self.message:
        return 'MatrixError, {0} '.format(self.message)
    else:
        return 'MatrixError has been raised'

In [0]:
import numpy as np

def conv2d(input_mat, kernel_mat):
  # grabbing the dimensions of the inputs
  kernel_dim = kernel_mat.shape[0]
  input_dim = input_mat.shape[0]

  # calculating the output dimensions
  out_dim = input_dim - kernel_dim + 1

  # making sure the inputs have valid sizes
  if out_dim < 1 or kernel_dim < 1 or input_dim < 1:
    raise MatrixError('Matrices can not have 0 or negative dimensions')
  if kernel_mat.shape[0] != kernel_mat.shape[1] or input_mat.shape[0] != input_mat.shape[1]:
    raise MatrixError('Matrices must be squares')
 

  # declaring and initializing the convolved feature
  out_mat = np.zeros((out_dim, out_dim))
  for i in range(out_dim):
      for j in range(out_dim):
        # applying the filter to each tile and outputting it to the matrix
          out_mat[i][j] = np.sum(input_mat[i:i+kernel_dim, j:j+kernel_dim]*kernel_mat)
  return out_mat

In [0]:
from scipy import signal
import numpy as np

input_mat = []
kernel_mat = []
expected_mat = []

# test case 1
input_mat.append(np.array([[1, 2, 1, 2],
                      [2, 1, 2, 1],
                      [1, 2, 1, 2],
                      [2, 1, 2, 1]]))

kernel_mat.append(np.array([[1, 0],
                       [0, 1]]))

expected_mat.append(np.array([[2, 4, 2],
                                [4, 2, 4],
                                [2, 4, 2]]))

# test case 2
input_mat.append(np.array([[1, 0, 0, 0],
                      [0, 1, 0, 0],
                      [0, 0, 1, 0],
                      [0, 0, 0, 1]]))
kernel_mat.append(np.array([[1, 0], [0, 1]]))
expected_mat.append(np.array([[2, 0, 0], [0, 2, 0], [0, 0, 2]]))


# test case 3
input_mat.append(np.array([[1, 0, 0, 0],
                      [0, 1, 0, 0],
                      [0, 0, 1, 0],
                      [0, 0, 0, 1]]))
kernel_mat.append(np.array([[1, -1],
                       [-1, 0]]))

expected_mat.append(np.array([[ 1, -1,  0], [-1,  1, -1],[ 0, -1,  1]]))


# test case 4
input_mat.append(np.array([[1, 0, 0, 0],
                      [0, 1, 0, 0],
                      [0, 0, 1, 0],
                      [0, 0, 0, 1]]))
kernel_mat.append(np.array([[1, 0, 0, 0],
                      [0, 1, 0, 0],
                      [0, 0, 1, 0],
                      [0, 0, 0, 1]]))

expected_mat.append(np.array([[4]]))


# test case 5 - should either through an error, or return empty matrix
input_mat.append(np.array([[1, -1],
                       [-1, 0]]))
kernel_mat.append(np.array([[1, 0, 0, 0],
                      [0, 1, 0, 0],
                      [0, 0, 1, 0],
                      [0, 0, 0, 1]]))

expected_mat.append([])



for i in range(len(input_mat)):
  # uncomment line for student code testing
  output_mat = conv2d(input_mat[i], kernel_mat[i])

  # uncomment lines below (and comment line above) for generating test cases.
  # if input_mat[i].shape[0] < kernel_mat[i].shape[0]:
  #   output_mat = []
  # else:
  #   output_mat = signal.convolve2d(input_mat[i], kernel_mat[i], mode='valid')

  print(output_mat)
  if np.array_equal(output_mat, expected_mat[i]):
    print("Correct output!\n")
  else:
    print("Incorrect output!\n")

[[2. 4. 2.]
 [4. 2. 4.]
 [2. 4. 2.]]
Correct output!

[[2. 0. 0.]
 [0. 2. 0.]
 [0. 0. 2.]]
Correct output!

[[ 1. -1.  0.]
 [-1.  1. -1.]
 [ 0. -1.  1.]]
Correct output!

[[4.]]
Correct output!



MatrixError: ignored

Problem 2

Using only numpy, implement the function maxpooling2d. It takes as input input_mat and s and outputs output_mat. The variables input_mat and output_mat are square matrices and s is an integer. It should compute the maxpooling operation on input_mat using window of shape s times s.

In [0]:
import numpy as np
from collections import deque

def maxpooling2d(input_mat, s):
  # grabbing the dimensions of the inputs
  input_dim = input_mat.shape[0]

  # making sure the inputs have valid sizes
  if input_dim < 1 or input_mat.shape[0] != input_mat.shape[1]:
    raise MatrixError('Matrices can not have 0 or negative dimensions')

  if input_mat.shape[0] != input_mat.shape[1]:
    raise MatrixError('Matrices must be squares')

  # declaring and initializing the convolved feature
  q = deque()
  out_dim = 0
  for i in range(0, input_dim, s):
      out_dim+=1
      for j in range(0, input_dim, s):
          # iterating through pools of size s and finding the max
          q.append(np.max(input_mat[i:i+s, j:j+s]))
          # print(input_mat[i:i+s, j:j+s])
          # print(np.max(input_mat[i:i+s, j:j+s]))
  
  out_mat = np.zeros((out_dim, out_dim))
  for i in range(out_dim):
    for j in range(out_dim):
      out_mat[i][j] = q.popleft()
      # print(out_mat[i][j])

  return out_mat

In [0]:
import skimage.measure

input_mat = []
expected_mat = []
s = []
input_mat.append(np.array([[1, 2, 1, 2],
                      [2, 4, 2, 1],
                      [1, 2, 4, 2],
                      [2, 1, 2, 1]]))
s.append(2)

expected_mat.append(np.array([[4, 2],
                                [2, 4]]))

input_mat.append(np.array([[1, 2, 1, 2, 4, 5],
                      [2, 4, 2, 1, 0, 3],
                      [1, 2, 4, 2, 4, 5],
                      [2, 1, 2, 1, 2, 1],
                      [1, 1, 2, 3, 1, 2],
                      [1, 1, 2, 3, 1, 2]]))
s.append(2)

expected_mat.append([[4, 2, 5],
 [2, 4, 5],
 [1, 3, 2]])


for i in range(len(input_mat)):
  # uncomment top line and comment second line to test code
  output_mat = maxpooling2d(input_mat[i], s[i])
  # output_mat = skimage.measure.block_reduce(input_mat[i], (s[i],s[i]), np.max)

  print(output_mat)

  if np.array_equal(output_mat, expected_mat[i]):
    print("Correct output!")
  else:
    print("Incorrect output!")

[[4. 2.]
 [2. 4.]]
Correct output!
[[4. 2. 5.]
 [2. 4. 5.]
 [1. 3. 2.]]
Correct output!
